### ISSUE TITLE
handle the addition of files to ConfigMaps

### ISSUE THREAD

**Issue by MarkHooijkaas** [MarkHooijkaas/kisst.kreate#15]
The konfig of a ConfigMap could be something like:
```
ConfigMap:
  demo-files:
    files:
      - logback.xml
      - application.properties
```
In the appdef we could specify where those files can be found. E.g.
```
files:
  logback.xml: "py:kreate.org.files:logback.xml"
  application.properties: ./files/applications.properties
```
The logback.xml will be loaded from the kreate.org.files module

It would also be nice to kreate files from a jinja template

For secret files something similar can be used with extra dekrypting the file
