### ISSUE TITLE
possibility to create new templates for patches

### ISSUE THREAD

**Issue by MarkHooijkaas** [MarkHooijkaas/kisst.kreate#4]

**Comment by MarkHooijkaas** [comment]
It is already possible to override templates, and keep the class
it is also possible to kreate new templates, but the Base class will be Resource.

Next to this code
``` 
templates:
  MyUdpService: ./templates/MyUdpService.yaml
  Service: ./templates/MyUdpService.yaml   # Override existing Service template
```

We might add something like
```
patch_templates:
  MyPatch: ./templates/MyPatch.yaml
```
This can be done in the KubeApp class

**Comment by MarkHooijkaas** [comment]
A Nice generic solution would be to have the template to have to different types of parameters
- if it is a string it would be the path of the template
- if it is a dict, it would have a filename attribute, and a class attribute, e.g.
```
templates:
  MyUdpService: ./templates/MyUdpService.yaml
  MyPatch:
    filename: ./templates/MyPatch.yaml
    class: kreate.kube.Patch

**Comment by MarkHooijkaas** [comment]
An alternative is implemented, to have a separate section in appdef.yaml:
```
templates:
  MyUdpService: ./templates/MyUdpService.yaml
  Service: ./templates/MyUdpService.yaml   # Override existing Service template
patch_templates:
  DemoPatch: ./templates/MyUdpService.yaml
```
 It works, but invoking the template does not work yet
